version: '3'
services:
  pg_chainlink:
    image: "postgres"
    ports:
      - "5440:5440"
    env_file:
      - database.env
    volumes:
      # [PATH_TO_POSTGRES_DATA]:/var/lib/postgressql/data/
      - ./chainlink-volume/:/var/lib/postgressql/data/
  chainlink:
    image: "smartcontract/chainlink"
    env_file: .env
    depends_on:
      - pg_chainlink
    ports:
      - "6688:6688"
    volumes:
      # [PATH_TO_REPO_CHAINLINK_VOLUME]:/chainlink/
      - /Users/casper.local/Desktop/Dev/blockchain_Link/chainlink-fun/run-node/chainlink-volume/:/chainlink/
    command: node start --password /chainlink/password.txt --api /chainlink/apicredentials.txt