version: '3'
services:
  pg_chainlink:
    image: "postgres"
    ports:
      - "5440:5440"
    env_file:
      - database.env
    volumes:
      # [PATH_TO_POSTGRES_DATA]:/var/lib/postgressql/data/
      - ./chainlink_app_contracts-volume/:/var/lib/postgressql/data/
  chainlink:
    image: "smartcontract/chainlink"
    env_file: .env
    depends_on:
      - pg_chainlink
    ports:
      - "6688:6688"
    volumes:
      # [PATH_TO_REPO_CHAINLINK_VOLUME]:/chainlink_app_contracts/
      #/Users/casper.local/Desktop/Dev/blockchain_Link/chainlink-fun/chainlink_app_contracts
      - /Users/casper.local/Desktop/Dev/blockchain_Link/chainlink_app_contracts-fun/run-node/chainlink_app_contracts-volume/:/chainlink_app_contracts/
    command: node start --password /Users/casper.local/Desktop/Dev/blockchain_Link/chainlink-fun/run-node/chainlink-volume/password.txt --api /Users/casper.local/Desktop/Dev/blockchain_Link/chainlink-fun/run-node/chainlink-volume/apicredentials.txt